package com.devloveops.zeus.domain.system;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table system_user
 */
@Data
public class ExSystemUser extends SystemUser {

    /**
     * 密码
     */
    @JsonIgnore
    private String password;
}