package com.devloveops.zeus.domain.system;

import java.util.Date;
import lombok.*;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table system_role
 */
@Data
public class SystemRole {
    /**
     * 
     */
    private Integer id;

    /**
     * 角色ID
     */
    private String roleId;

    /**
     * 角色名称
     */
    private String roleName;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 角色描述
     */
    private String description;
}